### ISSUE TITLE
[Bug Report] - Encoders

### ISSUE THREAD

**Issue by wandersoncferreira** [wandersoncferreira/helm-spotify-plus#12]
Need to see who is causing this: Spotify API or Helm when creating the candidates.

Might have possible solutions for both scenarios.

Example: 
[Imgur](http://i.imgur.com/pQKfjZ7.png)

**Comment by lgmoneda** [comment]
```
(encode-coding-string "São Gonçalo" 'utf-8)
    -> "SÃ£o GonÃ§alo" 
```
While it should be encoded in iso-8859-1.

**Comment by wandersoncferreira** [comment]
Solved!
