### ISSUE TITLE
`helm-spotify` and remote hosts

### ISSUE THREAD

**Issue by siwica** [wandersoncferreira/helm-spotify-plus#16]
When using `helm-spotify` it always bothered me that the `dbus-send` command was executed on the host the current buffer was currently visiting. When working on buffers visiting a remote host (which I am doing most of the time) this made it necessary so switch to some "local" buffer, execute `helm-spotify` from there and switch back to the original "remote" buffer afterwards.

Can this version of helm-spotify deal with this issue? Having some variable that can be configured to make  `helm-spotify` always being executed on the original host would be nice!

**Comment by wandersoncferreira** [comment]
hi @siwica we will work on it.

I think it will be easier to provide the feature you are describing. The problem might be due the **shell-command** used. It would be better to use **call-process** and verify for example:

```shell
call-process "/bin/bash"
```
For executions only at the original host and the **shell-command** otherwise.

**Comment by wandersoncferreira** [comment]
@siwica the PR #19 works fine for Linux distros.  Variable _helm-spotify-plus-dbus-prefer-local_ control this behavior. Default is to use local dbus.

Please see the [demo](https://youtu.be/XKsKUDMAPI4).

all windows users are welcome to contribute to this PR.

**Comment by siwica** [comment]
Cool, thank you. That was quick! 

Maybe `helm-spotify-plus-dbus-prefer-local` should be made customizable by using `defcustom` instead of `defcustom` though.

**Comment by wandersoncferreira** [comment]
Great! I will make the correction. Thanks
