### ISSUE TITLE
Problem with playing the album function

### ISSUE THREAD

**Issue by Doxdrum** [wandersoncferreira/helm-spotify-plus#25]
First of all, thank you for the package.

I'm using `helm-spotify-plus` to search an artist, `a: dream theater` and I get the results in the helm interface. However, standing on a song I press `TAB` and get the functionality *play albun*. It starts to play, but it keep repeating over and over the same song!

**Comment by lgmoneda** [comment]
@Doxdrum what's your operational system?

**Comment by Doxdrum** [comment]
@lgmoneda Linux (Debian jessie), but I'm using emacs 25.1 (compiled from the git repository)

**Comment by lgmoneda** [comment]
@Doxdrum Does it jump to the album's first track, play that track and then loop or does it play the track selected even if it's not the album's first track? It should jump to the first track. 

I've tested playing album from its first track, from other tracks, with spotify loop activated and it's always jumping to the next song. 

We've tested here in Emacs 24.4.1 and 25.1, both Debian Jessie, and it's working in both.

**Comment by Doxdrum** [comment]
@lgmoneda Sometimes it does not play the first song. I'm trying again the looping... let me wait a few minutes. I'll feedback!

**Comment by lgmoneda** [comment]
Ok, @Doxdrum! 
Can you tell us what was your query exactly? And which item have you selected? Then we can check if there's a specific problem happening.

**Comment by Doxdrum** [comment]
@lgmoneda It is working! It seems to be a problem of the disc I was hearing previously. Weird!

BTW: great work!

**Comment by lgmoneda** [comment]
Great, @Doxdrum! Thanks :D
