### ISSUE TITLE
How to bind prefix for helm-spotify-plus-<ACTION>

### ISSUE THREAD

**Issue by sunwukung** [wandersoncferreira/helm-spotify-plus#26]
My emacs-fu is not the sharpest - could you give me some idea how to bind a prefix key so that I can use this more efficiently in helm without M-x? As I understand it there is no available command prefix? I tried this but obvs it captures the s first: 

```
  (global-set-key (kbd "C-c s") 'helm-spotify-plus)
  (global-set-key (kbd "C-c s f") 'helm-spotify-plus-next)
  (global-set-key (kbd "C-c s b") 'helm-spotify-plus-previous)
  (global-set-key (kbd "C-c s p") 'helm-spotify-plus-play)
  (global-set-key (kbd "C-c s s") 'helm-spotify-plus-pause)
```

Sorry if this isn't the appropriate place to ask this question

**Comment by wandersoncferreira** [comment]
I would like to suggest two approaches:

#### No extra packages needed
```emacs-lisp
  (global-set-key (kbd "C-c s s") 'helm-spotify-plus)  ;; s for SEARCH
  (global-set-key (kbd "C-c s f") 'helm-spotify-plus-next)
  (global-set-key (kbd "C-c s b") 'helm-spotify-plus-previous)
  (global-set-key (kbd "C-c s p") 'helm-spotify-plus-play) 
  (global-set-key (kbd "C-c s g") 'helm-spotify-plus-pause) ;; g cause you know.. C-g stop things :)
```

However, if you are willing to use another package. Your usage case is exactly the **hydra** package.
```emacs-lisp
(defhydra hydra-spotify (global-map "C-c s")
  "helm-spotify-plus"
 ("s" helm-spotify-plus)
 ("f" helm-spotify-plus-next)
 ("b" helm-spotify-plus-previous)
 ("p" helm-spotify-plus-play)
 ("g" helm-spotify-plus-pause))
```

Check [hydra package](https://github.com/abo-abo/hydra) to see what else you can do with it.

I would like to add your idea of keybindings (global-set option) to the README of this project. If you are interested in doing do, you could push a pull request for it too.

Great work!

**Comment by wandersoncferreira** [comment]
Keys added in README. Thanks.
