### ISSUE TITLE
Decide about API request and search in results

### ISSUE THREAD

**Issue by lgmoneda** [wandersoncferreira/helm-spotify-plus#3]
Should new requests be done while the query string is typed? Append the new results?
Should it switch to a helm style search in results after a "query + RET"?

I think it's going to be clearer after the other improvements in search which one will be more useful to user, but the frequency of API requests need to be addressed!

**Comment by wandersoncferreira** [comment]
Related improvements:

- [ ] Verify how much time each part of the code is taking to perform its action
- [ ] Improve bad recursive calls in the code
