### ISSUE TITLE
not playing

### ISSUE THREAD

**Issue by Githeo** [wandersoncferreira/helm-spotify-plus#30]
Hello,

I just updated all the packages. After searching the song and clicking on it to play I get the following:
`30:40 syntax error: A identifier can't go after this identifier. (-2740)`

**Comment by wandersoncferreira** [comment]
Hello,

Which OS are you using? I am testing on OSX here now and everything works file.
Do you mind sharing the exact search you performed?

Thanks

**Comment by Githeo** [comment]
Yes, sorry. I'm on a macOS Sierra 10.12.6. 
It's reproduced for any search. I just searched for a metallica song.

**Comment by wandersoncferreira** [comment]
@Githeo I can't reproduce it. I am also using macOS Sierra... See this screencast from the same search

https://vimeo.com/250005357

**Comment by Githeo** [comment]
Resolved updating the system. Thanks @wandersoncferreira.

**Comment by aardito2** [comment]
I am seeing the same issue on High Sierra.
