### ISSUE TITLE
Queue functionality question

### ISSUE THREAD

**Issue by wandersoncferreira** [wandersoncferreira/helm-spotify-plus#37]
@kahole I was reading the code more carefully today and I noticed that we have this section of code:
https://github.com/wandersoncferreira/helm-spotify-plus/blob/5bace41e41cf9c677d5d0e203dd6ca66110accdd/helm-spotify-plus.el#L105

If I have 1 or more than 2 songs in the queue I will not call the correct function to play the next queued song. Is it right? Or I'm missing something?

**Comment by kahole** [comment]
**This is a mistake, yes. It should be greater than or equal to 2.**
Because the currently playing track is the first element in the queue, so if there is 2 or more tracks total in the queue, we call the queue-next variant, and otherwise we call the normal next-track functions.
