### ISSUE TITLE
Music not playing / no sound

### ISSUE THREAD

**Issue by mohammadanton** [wandersoncferreira/helm-spotify-plus#39]
I search it show the list of song but when I choose it, the helm pop up is gone, but no song is played

**Comment by wandersoncferreira** [comment]
Sorry for the late response.

Could you worked out this problem? Can you give us more information about the specific problem?

**Comment by Renzix** [comment]
this is happening for me as well
![image](https://user-images.githubusercontent.com/31043283/61682156-79f00100-acde-11e9-8024-3b37bd41ce72.png)
Keep in mind im also on the latest emacs from git and built it myself
GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu)
 of 2019-07-23

I can provide more info if needed

**Comment by wandersoncferreira** [comment]
I could not reproduce this issue. @Renzix can you provide more info? Maybe using `debug-on-error` to `t` and sending the stack error would help me.

**Comment by Renzix** [comment]
I just redownloaded it and it worked fine this time??? I'm pretty sure I tested it pretty thoroughly but maybe spotify api was down or something sorry about that.

**Comment by wandersoncferreira** [comment]
@Renzix no problem. I'll close the issue now, if anything happen just let us know. I'm more aware of the github notifications now. thanks
