### ISSUE TITLE
"an Track" typo

### ISSUE THREAD

**Issue by mcncm** [wandersoncferreira/helm-spotify-plus#42]
Hi there,
First, I love this tool! Thanks for maintaining it. There's a small (but jarring) typo in helm-spotify-plus.el. "an Track" should read "a Track" or "a track" (depending on your preferred capitalization convention--the latter looks better to me, but that's up to you). There are a few in the README as well, but this is perhaps less important.

Thanks!

**Comment by wandersoncferreira** [comment]
Fixed  by the PR d8f1ee6cfedf1f9d5720237f20a869506b991876

**Comment by wandersoncferreira** [comment]
I also tried to improve the readability from the README page. Thanks for pointing out
