### ISSUE TITLE
Not playing after pausing

### ISSUE THREAD

**Issue by ihowell** [wandersoncferreira/helm-spotify-plus#45]
Everything seems to work, except that when I attempt to play music after pausing it, it simply stays paused. I get the message `(Shell command completed with no ouptut)`, but music does not start playing again.

I'm running Mac OS X v10.14.6 on a Macbook Pro 2018. What else would be helpful in debugging this?

**Comment by wandersoncferreira** [comment]
This issue is fixed with your PR?

**Comment by ihowell** [comment]
Yes it was, I'll close this.
